# for usage with dense_pose_pcvp/1.0.1@semsa/unstable

# obj_000001:
#   ckpt: "/volume/projects/project_semsa/vision_db/trained_models/ycbv/dense_pose/11-58-13_local_ycbv-obj_000001_Ranger_lr0.0003_wd0.001_bs1x32/checkpoints/last.ckpt"
#   mesh:
#     path: "/volume/pekdat/datasets/public/NOT_SAVED_TO_BACKUP/BOP_DATASETS/ycbv/models/obj_000001.ply"
#     unit: "mm"

obj_000002:
  ckpt: "/volume/projects/project_semsa/model_dojo/ycbv/3.0.0/ProudWolverine_eagernext_ycbv-02_bs1x24/checkpoints/last.ckpt"
  mesh:
    path: "/volume/pekdat/datasets/public/NOT_SAVED_TO_BACKUP/BOP_DATASETS/ycbv/models/obj_000002.ply"
    unit: "mm"

# obj_000003:
#   ckpt: "/volume/projects/project_semsa/vision_db/trained_models/ycbv/dense_pose/11-58-40_local_ycbv-obj_000003_Ranger_lr0.0003_wd0.001_bs1x32/checkpoints/last.ckpt"
#   mesh:
#     path: "/volume/pekdat/datasets/public/NOT_SAVED_TO_BACKUP/BOP_DATASETS/ycbv/models/obj_000003.ply"
#     unit: "mm"
#
# obj_000004:
#    ckpt: "/volume/projects/project_semsa/vision_db/trained_models/ycbv/dense_pose/11-58-51_local_ycbv-obj_000004_Ranger_lr0.0003_wd0.001_bs1x32/checkpoints/last.ckpt"
#    mesh:
#       path: "/volume/pekdat/datasets/public/NOT_SAVED_TO_BACKUP/BOP_DATASETS/ycbv/models/obj_000004.ply"
#       unit: "mm"
#
# obj_000005:
#    ckpt: "/volume/projects/project_semsa/vision_db/trained_models/ycbv/dense_pose/11-58-07_local_ycbv-obj_000005_Ranger_lr0.0003_wd0.001_bs1x32/checkpoints/last.ckpt"
#    mesh:
#       path: "/volume/pekdat/datasets/public/NOT_SAVED_TO_BACKUP/BOP_DATASETS/ycbv/models/obj_000005.ply"
#       unit: "mm"
#
# obj_000006:
#   ckpt: "/volume/projects/project_semsa/vision_db/trained_models/ycbv/dense_pose/11-58-19_local_ycbv-obj_000006_Ranger_lr0.0003_wd0.001_bs1x32/checkpoints/last.ckpt"
#   mesh:
#     path: "/volume/pekdat/datasets/public/NOT_SAVED_TO_BACKUP/BOP_DATASETS/ycbv/models/obj_000006.ply"
#     unit: "mm"
#
# obj_000007:
#   ckpt: "/volume/projects/project_semsa/vision_db/trained_models/ycbv/dense_pose/11-58-35_local_ycbv-obj_000007_Ranger_lr0.0003_wd0.001_bs1x32/checkpoints/last.ckpt"
#   mesh:
#      path: "/volume/pekdat/datasets/public/NOT_SAVED_TO_BACKUP/BOP_DATASETS/ycbv/models/obj_000007.ply"
#      unit: "mm"
#
# obj_000008:
#    ckpt: "/volume/projects/project_semsa/vision_db/trained_models/ycbv/dense_pose/10-08-40_local_ycbv-obj_000008_Ranger_lr0.0003_wd0.001_bs1x32/checkpoints/last.ckpt"
#    mesh:
#      path: "/volume/pekdat/datasets/public/NOT_SAVED_TO_BACKUP/BOP_DATASETS/ycbv/models/obj_000008.ply"
#      unit: "mm"
#
# obj_000009:
#   ckpt: "/volume/projects/project_semsa/vision_db/trained_models/ycbv/dense_pose/17-03-15_local_ycbv-obj_000009_Ranger_lr0.0003_wd0.001_bs1x32/checkpoints/last.ckpt"
#   mesh:
#     path: "/volume/pekdat/datasets/public/NOT_SAVED_TO_BACKUP/BOP_DATASETS/ycbv/models/obj_000009.ply"
#     unit: "mm"
#
# obj_000010:
#   ckpt: "/volume/projects/project_semsa/vision_db/trained_models/ycbv/dense_pose/17-09-34_local_ycbv-obj_000010_Ranger_lr0.0003_wd0.001_bs1x32/checkpoints/last.ckpt"
#   mesh:
#     path: "/volume/pekdat/datasets/public/NOT_SAVED_TO_BACKUP/BOP_DATASETS/ycbv/models/obj_000010.ply"
#     unit: "mm"
