echo Restoring environment
unset CONAN_FASTAPI_ROOT
export PYTHONPATH='/opt/rmc-build-tools/any/ws_gui/src:/opt/rmc-build-tools/any/cissy2/python3::/opt/rmc-build-tools/ubuntu2404-x86_64/python-pkgs'
export PATH='/home/reic_al/miniforge3/condabin:/opt/rmc-build-tools/ubuntu2404-x86_64/python-pkgs/bin:/opt/rmc-build-tools/any/seqmedit:/opt/rmc-build-tools/any/ws_gui/bin:/opt/rmc-build-tools/any/cissy2/bin/linux:/opt/rmc-build-tools/any/scripts:/home/reic_al/bin/ubuntu2404-x86_64:/usr/local/sbin:/usr/local/bin:/usr/sbin:/opt/TeXLive/latest/bin/x86_64-linux:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/quest/bin:/home/reic_al/.fzf/bin'
unset CONAN_ANNOTATED_DOC_ROOT
unset CONAN_PYDANTIC_ROOT
unset CONAN_ANNOTATED_TYPES_ROOT
unset CONAN_PYDANTIC_CORE_ROOT
unset CONAN_TYPING_INSPECTION_ROOT
unset CONAN_TYPING_EXTENSIONS_ROOT
unset CONAN_STARLETTE_ROOT
unset CONAN_PCVP_CLIENT_PY_ROOT
unset LD_LIBRARY_PATH
unset DYLD_LIBRARY_PATH
unset CONAN_PCVP_CLIENT_CPP_ROOT
unset CONAN_PCVP_PROTOCOL_ROOT
unset CONAN_TCLAP_ROOT
unset CONAN_PCVP_COMMON_ROOT
unset CONAN_PSTREAMS_ROOT
unset CONAN_LOG4CXX_ROOT
unset CONAN_PYBIND11_OPENCV_NUMPY_ROOT
unset CONAN_OPENCV_PYTHON_ROOT
unset CONAN_UVICORN_ROOT
unset CONAN_PYTHON_MULTIPART_ROOT
unset LN_MESSAGE_DEFINITION_DIRS
unset CONAN_PRE_COMMIT_ROOT
unset CONAN_CFGV_ROOT
unset CONAN_IDENTIFY_ROOT
unset CONAN_NODEENV_ROOT
