script_folder="/home/reic_al/repositories/guide_dog/application/mockup_pipeline/cissygen/cissy_workspace/reic_al/ubuntu2404-x86_64/process/yolov7_pcvp"
echo "echo Restoring environment" > "$script_folder/deactivate_conanrunenv-relwithdebinfo-x86_64.sh"
for v in CONAN_YOLOV7_PCVP_ROOT PYTHONPATH PATH CONAN_PCVP_CLIENT_PY_ROOT LD_LIBRARY_PATH DYLD_LIBRARY_PATH CONAN_PCVP_CLIENT_CPP_ROOT CONAN_PCVP_PROTOCOL_ROOT CONAN_TCLAP_ROOT CONAN_PCVP_COMMON_ROOT CONAN_PSTREAMS_ROOT CONAN_LOG4CXX_ROOT CONAN_PYBIND11_OPENCV_NUMPY_ROOT CONAN_YOLOV7_ROOT CONAN_TORCHVISION_ROOT CONAN_TORCH_ROOT CONAN_FSSPEC_ROOT CONAN_NETWORKX_ROOT CONAN_NVIDIA_CUDA_CUPTI_CU12_ROOT CONAN_NVIDIA_CUDA_NVRTC_CU12_ROOT CONAN_NVIDIA_CUDA_RUNTIME_CU12_ROOT CONAN_NVIDIA_CUDNN_CU12_ROOT CONAN_NVIDIA_CUFFT_CU12_ROOT CONAN_NVIDIA_CUFILE_CU12_ROOT CONAN_NVIDIA_CURAND_CU12_ROOT CONAN_NVIDIA_CUSOLVER_CU12_ROOT CONAN_NVIDIA_CUBLAS_CU12_ROOT CONAN_NVIDIA_CUSPARSE_CU12_ROOT CONAN_NVIDIA_CUSPARSELT_CU12_ROOT CONAN_NVIDIA_NCCL_CU12_ROOT CONAN_NVIDIA_NVJITLINK_CU12_ROOT CONAN_NVIDIA_NVSHMEM_CU12_ROOT CONAN_NVIDIA_NVTX_CU12_ROOT CONAN_SYMPY_ROOT CONAN_MPMATH_ROOT CONAN_TRITON_ROOT CONAN_TENSORBOARD_ROOT CONAN_ABSL_PY_ROOT CONAN_GRPCIO_ROOT CONAN_MARKDOWN_ROOT CONAN_PROTOBUF_ROOT CONAN_TENSORBOARD_DATA_SERVER_ROOT CONAN_WERKZEUG_ROOT CONAN_SEABORN_ROOT CONAN_TQDM_ROOT CONAN_OPENCV_PYTHON_ROOT
do
   is_defined="true"
   value=$(printenv $v) || is_defined="" || true
   if [ -n "$value" ] || [ -n "$is_defined" ]
   then
       echo export "$v='$value'" >> "$script_folder/deactivate_conanrunenv-relwithdebinfo-x86_64.sh"
   else
       echo unset $v >> "$script_folder/deactivate_conanrunenv-relwithdebinfo-x86_64.sh"
   fi
done

export CONAN_YOLOV7_PCVP_ROOT="/volume/conan_cache/reic_al/.conan2/p/b/yolovd30cf3992f120/p"
export PYTHONPATH="$PYTHONPATH:/volume/conan_cache/reic_al/.conan2/p/opencf1da687316789/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/tqdmf9240d0ab52b0/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/seabo6d6b17f6bab82/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/werkz3437a2af7ed38/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/tensocf22cd495f17a/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/proto4ea247dd76b16/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/markdabfd8a20aaed4/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/grpci8c01f2a3d7eba/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/absl-60e1a7641b923/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/tensob1d6e9ff9b7bd/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/trito15a20cf86e29d/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/mpmat5b8b1ee33e1d4/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/sympyd822a8b334571/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/nvidi3924bbe4f5cb4/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/nvidic224ae4ebf036/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/nvidi2f5f8fee1037b/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/nvidid3593ab867a97/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/nvidiff32bbabf295c/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/nvidiba6b7e16d5622/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/nvidi5b1e19dc4619d/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/nvidi8e91166d29b2d/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/nvidi6927a05b55ea5/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/nvidib7fcb5916a0b0/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/nvidie109d7f9da3ab/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/nvidi904cdee85f126/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/nvidi4160ced0cca49/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/nvidi7bb892f313bed/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/nvidi6912ca0bbf249/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/netwoc3f97ca3beacc/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/fsspe89c93d719a5d4/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/torch4165e0c6ba50b/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/torchbd718096d7bb9/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/yolovf8d1ab69abb12/p/local/lib/python3.12/dist-packages:/volume/conan_cache/reic_al/.conan2/p/pcvp_eeaed569c9331/p/lib:/volume/conan_cache/reic_al/.conan2/p/b/yolovd30cf3992f120/p/local/lib/python3.12/dist-packages"
export PATH="/volume/conan_cache/reic_al/.conan2/p/b/yolovd30cf3992f120/p/local/bin:/volume/conan_cache/reic_al/.conan2/p/pcvp_99ff97274e5a3/p/bin:/volume/conan_cache/reic_al/.conan2/p/yolovf8d1ab69abb12/p/local/bin:/volume/conan_cache/reic_al/.conan2/p/torch4165e0c6ba50b/p/local/bin:/volume/conan_cache/reic_al/.conan2/p/sympyd822a8b334571/p/local/bin:/volume/conan_cache/reic_al/.conan2/p/trito15a20cf86e29d/p/local/bin:/volume/conan_cache/reic_al/.conan2/p/tensob1d6e9ff9b7bd/p/local/bin:/volume/conan_cache/reic_al/.conan2/p/markdabfd8a20aaed4/p/local/bin:/volume/conan_cache/reic_al/.conan2/p/tqdmf9240d0ab52b0/p/local/bin:$PATH"
export CONAN_PCVP_CLIENT_PY_ROOT="/volume/conan_cache/reic_al/.conan2/p/pcvp_eeaed569c9331/p"
export LD_LIBRARY_PATH="/volume/conan_cache/reic_al/.conan2/p/pcvp_eeaed569c9331/p/lib:/volume/conan_cache/reic_al/.conan2/p/pcvp_4dd8aed650c95/p/lib:/volume/conan_cache/reic_al/.conan2/p/pcvp_99ff97274e5a3/p/lib:/volume/conan_cache/reic_al/.conan2/p/tclapf04bf9560c7f1/p/lib:/volume/conan_cache/reic_al/.conan2/p/liblib459dcf8618a3/p/lib:/volume/conan_cache/reic_al/.conan2/p/pcvp_bcb634da30b78/p/lib:/volume/conan_cache/reic_al/.conan2/p/log4cb6e00c6f44d7b/p/lib:$LD_LIBRARY_PATH:/volume/conan_cache/reic_al/.conan2/p/liblib459dcf8618a3/p/lib"
export DYLD_LIBRARY_PATH="/volume/conan_cache/reic_al/.conan2/p/pcvp_eeaed569c9331/p/lib:/volume/conan_cache/reic_al/.conan2/p/pcvp_4dd8aed650c95/p/lib:/volume/conan_cache/reic_al/.conan2/p/pcvp_99ff97274e5a3/p/lib:/volume/conan_cache/reic_al/.conan2/p/tclapf04bf9560c7f1/p/lib:/volume/conan_cache/reic_al/.conan2/p/liblib459dcf8618a3/p/lib:/volume/conan_cache/reic_al/.conan2/p/pcvp_bcb634da30b78/p/lib:/volume/conan_cache/reic_al/.conan2/p/log4cb6e00c6f44d7b/p/lib:$DYLD_LIBRARY_PATH"
export CONAN_PCVP_CLIENT_CPP_ROOT="/volume/conan_cache/reic_al/.conan2/p/pcvp_4dd8aed650c95/p"
export CONAN_PCVP_PROTOCOL_ROOT="/volume/conan_cache/reic_al/.conan2/p/pcvp_99ff97274e5a3/p"
export CONAN_TCLAP_ROOT="/volume/conan_cache/reic_al/.conan2/p/tclapf04bf9560c7f1/p"
export CONAN_PCVP_COMMON_ROOT="/volume/conan_cache/reic_al/.conan2/p/pcvp_bcb634da30b78/p"
export CONAN_PSTREAMS_ROOT="/volume/conan_cache/reic_al/.conan2/p/pstre6b62fb282e173/p"
export CONAN_LOG4CXX_ROOT="/volume/conan_cache/reic_al/.conan2/p/log4cb6e00c6f44d7b/p"
export CONAN_PYBIND11_OPENCV_NUMPY_ROOT="/volume/conan_cache/reic_al/.conan2/p/pybin846fb3f6916a8/p"
export CONAN_YOLOV7_ROOT="/volume/conan_cache/reic_al/.conan2/p/yolovf8d1ab69abb12/p"
export CONAN_TORCHVISION_ROOT="/volume/conan_cache/reic_al/.conan2/p/torchbd718096d7bb9/p"
export CONAN_TORCH_ROOT="/volume/conan_cache/reic_al/.conan2/p/torch4165e0c6ba50b/p"
export CONAN_FSSPEC_ROOT="/volume/conan_cache/reic_al/.conan2/p/fsspe89c93d719a5d4/p"
export CONAN_NETWORKX_ROOT="/volume/conan_cache/reic_al/.conan2/p/netwoc3f97ca3beacc/p"
export CONAN_NVIDIA_CUDA_CUPTI_CU12_ROOT="/volume/conan_cache/reic_al/.conan2/p/nvidi6912ca0bbf249/p"
export CONAN_NVIDIA_CUDA_NVRTC_CU12_ROOT="/volume/conan_cache/reic_al/.conan2/p/nvidi7bb892f313bed/p"
export CONAN_NVIDIA_CUDA_RUNTIME_CU12_ROOT="/volume/conan_cache/reic_al/.conan2/p/nvidi4160ced0cca49/p"
export CONAN_NVIDIA_CUDNN_CU12_ROOT="/volume/conan_cache/reic_al/.conan2/p/nvidi904cdee85f126/p"
export CONAN_NVIDIA_CUFFT_CU12_ROOT="/volume/conan_cache/reic_al/.conan2/p/nvidie109d7f9da3ab/p"
export CONAN_NVIDIA_CUFILE_CU12_ROOT="/volume/conan_cache/reic_al/.conan2/p/nvidib7fcb5916a0b0/p"
export CONAN_NVIDIA_CURAND_CU12_ROOT="/volume/conan_cache/reic_al/.conan2/p/nvidi6927a05b55ea5/p"
export CONAN_NVIDIA_CUSOLVER_CU12_ROOT="/volume/conan_cache/reic_al/.conan2/p/nvidi8e91166d29b2d/p"
export CONAN_NVIDIA_CUBLAS_CU12_ROOT="/volume/conan_cache/reic_al/.conan2/p/nvidi5b1e19dc4619d/p"
export CONAN_NVIDIA_CUSPARSE_CU12_ROOT="/volume/conan_cache/reic_al/.conan2/p/nvidiba6b7e16d5622/p"
export CONAN_NVIDIA_CUSPARSELT_CU12_ROOT="/volume/conan_cache/reic_al/.conan2/p/nvidiff32bbabf295c/p"
export CONAN_NVIDIA_NCCL_CU12_ROOT="/volume/conan_cache/reic_al/.conan2/p/nvidid3593ab867a97/p"
export CONAN_NVIDIA_NVJITLINK_CU12_ROOT="/volume/conan_cache/reic_al/.conan2/p/nvidi2f5f8fee1037b/p"
export CONAN_NVIDIA_NVSHMEM_CU12_ROOT="/volume/conan_cache/reic_al/.conan2/p/nvidic224ae4ebf036/p"
export CONAN_NVIDIA_NVTX_CU12_ROOT="/volume/conan_cache/reic_al/.conan2/p/nvidi3924bbe4f5cb4/p"
export CONAN_SYMPY_ROOT="/volume/conan_cache/reic_al/.conan2/p/sympyd822a8b334571/p"
export CONAN_MPMATH_ROOT="/volume/conan_cache/reic_al/.conan2/p/mpmat5b8b1ee33e1d4/p"
export CONAN_TRITON_ROOT="/volume/conan_cache/reic_al/.conan2/p/trito15a20cf86e29d/p"
export CONAN_TENSORBOARD_ROOT="/volume/conan_cache/reic_al/.conan2/p/tensob1d6e9ff9b7bd/p"
export CONAN_ABSL_PY_ROOT="/volume/conan_cache/reic_al/.conan2/p/absl-60e1a7641b923/p"
export CONAN_GRPCIO_ROOT="/volume/conan_cache/reic_al/.conan2/p/grpci8c01f2a3d7eba/p"
export CONAN_MARKDOWN_ROOT="/volume/conan_cache/reic_al/.conan2/p/markdabfd8a20aaed4/p"
export CONAN_PROTOBUF_ROOT="/volume/conan_cache/reic_al/.conan2/p/proto4ea247dd76b16/p"
export CONAN_TENSORBOARD_DATA_SERVER_ROOT="/volume/conan_cache/reic_al/.conan2/p/tensocf22cd495f17a/p"
export CONAN_WERKZEUG_ROOT="/volume/conan_cache/reic_al/.conan2/p/werkz3437a2af7ed38/p"
export CONAN_SEABORN_ROOT="/volume/conan_cache/reic_al/.conan2/p/seabo6d6b17f6bab82/p"
export CONAN_TQDM_ROOT="/volume/conan_cache/reic_al/.conan2/p/tqdmf9240d0ab52b0/p"
export CONAN_OPENCV_PYTHON_ROOT="/volume/conan_cache/reic_al/.conan2/p/opencf1da687316789/p"